### ISSUE TITLE
CompositionType for DocType

### ISSUE THREAD

**Issue by naeazach** [nicbell/ucreate#10]
In the DocType  example you use this constructor:

`CompositionTypes = new[] { typeof(TaggedPage) }`

does this refer to the Umbraco page the new doc type would be nested under?  And would that page also need to be laid out code first?  

If so, is there an easy way to "export" a existing doc type to the ucrease code first format?

**Comment by nicbell** [comment]
`CompositionTypes` refers to doctype composition. If you just want normal nesting using inheritance. 

``` cs
[DocType(Name = "Home",
        Icon = "icon-black icon-home",
        AllowedAsRoot = true,
        AllowedTemplates = new[] { "Home" },
        AllowedChildTypes = new[] { typeof(BlogIndex) },
        CompositionTypes = new[] { typeof(TaggedPage) })]
    public class Home : Base {...}
```

`Home` will be created under `Base` using inheritance getting properties from `Base`, it will also get properties from `TaggedPage` using composition. Umbraco is smart like that.
