### ISSUE TITLE
Calling Sync at any time

### ISSUE THREAD

**Issue by blueboxes** [nicbell/ucreate#11]
Calling Ucreate can take time so we do not want it on for every app restart over 5 minutes. 
  
Ideally we would call the code in ConfigureUCreate.cs via an exposed method for adhock sync. Happy to make the change and raise a PR if you can see no issues and could recommend where to place the code.

**Comment by nicbell** [comment]
There is an internal method, `CmsSyncManger.SynchronizeIfNotSynchronized();` which will need to be made public.

**Comment by blueboxes** [comment]
I have created a PR #12 which achives this. It did not look like any Tests needed updating.

**Comment by nicbell** [comment]
Fixed by #12 thanks @blueboxes

**Comment by nicbell** [comment]
@blueboxes it's been released on Nuget. Thanks again.
