### ISSUE TITLE
Compatible with enabled PropertyValueConverters?

### ISSUE THREAD

**Issue by anve** [nicbell/ucreate#16]
This might be more of a question than an actual issue right now, but is ucreate compatible if running Umbraco with EnablePropertyValueConverters = true? 

I'm building upon your excellent library to get content types, properties etc etc strongly-typed and fully managed in version-controlled code (getting away from managing this in the back office for every site/server). Without diving into to all details, my feeling is that, if we enable the built-in property value converters, this makes any ucreate converters superfluous. But more importantly, it seems that the SetValues method of the BaseDocType can be very "heavy" (when the publishedProperty.Value is accessed) as it triggers series of additional SetValues calls when the BaseDocType is instantiated. Am I right about this or maybe have I missed something?

**Comment by nicbell** [comment]
Thanks for getting touch. UCreate was built before `EnablePropertyValueConverters` was added, I definitely should move towards using as much built-in stuff as possible.

What do you think off moving away from this:
```c#
[TypeConverter(typeof(ValueListConverter))]
[Property(Alias = "tags", TypeName = "Tag Picker", Name = "Tags", Description = "Tags", Mandatory = false, TabName = "Meta")]
public List<string> Tags { get; set; }
```
Towards something like this:
```c#
[Property(Alias = "tags", TypeName = "Tag Picker", Name = "Tags", Description = "Tags", Mandatory = false, TabName = "Meta")]
public IEnumerable<string> Tags { 
  get {
    return Content.GetPropertyValue<IEnumerable<string>>("tags");
  } 
}
```
It would leverage property value converters and remove setting from `BaseDocType`.

**Comment by nicbell** [comment]
@mstgelais what do you think about this for `v2`? Would only be able to support 7.6+.

**Comment by mstgelais** [comment]
Mmmmm... First, thanks for tagging me!

I've never played with type converters before, and only used UCreate the best way I could. Now I see that I might be "behind" you two on this one.

I would love to see more automation around the loading of pickers' data. For exemple, for a these classes:

```csharp
[DocType(Name = "Job Offer")]
public class JobOffer : Page /* Page is a BaseDocType */
{
    public JobOffer(IPublishedContent content) : base(content)
    {
    }

    [Property(Name = "Presented By - Team Member",
        Alias = nameof(TeamMember),
        TypeName = SingleTeamMemberPicker.Alias)]
    public string TeamMember { get; set; }
}

[DocType(Name = "Team Member",
    Icon = "icon-employee",
    AllowedAsRoot = false)]
public class TeamMember : BaseDocType
{
    public TeamMember(IPublishedContent content) : base(content)
    {
    }
}
```

I've extended the `UmbracoViewPage` and added several functions, like this one:

```csharp
public T GetContent<T>(string stringUdi) where T : BaseDocType
{
    /* This service only wraps the UmbracoHelper to help with unit tests. */
    return PublishedContentService.Get<T>(stringUdi);
}
```

And from a view, I can do this:

```csharp
@inherits DocTypeViewPage<JobOffer>

@{
    var teamMember = GetContent<TeamMember>(Model.TeamMember);
}
```

So I'm gonna go check on the type converters, and see what I can come up with. And yes: I would totally do this in a v2, supporting only 7.6 and up. No problem with that.

**Comment by nicbell** [comment]
@mstgelais this how is how I think it will work in V2 [Home.cs](https://github.com/nicbell/ucreate/blob/2dce0ea0a4660b70660ee577d9a64a9ca12447b4/NicBell.UCreate.Test/DocumentTypes/Home.cs#L54)

**Comment by anve** [comment]
@nicbell Yes, I like that suggestion, definitely a step in the right direction I think!

**Comment by nicbell** [comment]
V2 is now available.
