### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by dano8010** [nicbell/ucreate#5]
Hi Nic Bell,

I really like your plugin and I hope I get the privilege to use it in my future Umbraco projects. However. I've created a Doctype and a template and everything works fine. But when I add a page to the site tree (in this case root) and I try to visit the page ( "/") I get an "System.NullReferenceException: Object reference not set to an instance of an object.". Appearently nothing gets submitted to the constructor of the document type.

I'm running Umbraco 7.3.x so it might be due to the version, but I'm really curious wether I might be doing something wrong or if it's the project that's not up to date with Umbracos version.

Please keep in touch.

//
Daniel, Web developer, Sweden

**Comment by nicbell** [comment]
Hey Daniel, 

Are you getting UCreate via nuget? Also what version are you using?

I will upgrade my test project to 7.3 to see if I can reproduce this error.
If you want you can email me the code at me@nicbell.net

Kind regards, Nic

**Comment by nicbell** [comment]
I've Umbraco UCreate and the test project to Umbraco 7.3.1 and deployed to Nuget. 
It is working for me, let me know how you get on.

**Comment by dano8010** [comment]
Hi Nic,

Thanks for getting back to me. Okey. I will try further. Do install Umbraco
CMS through nuget as well? And is there perhaps a doctype parameter I've
forgot to submit that may cause this behaviour?

Regards
Daniel

On 5 November 2015 at 20:46, Nic Bell notifications@github.com wrote:

> I've Umbraco UCreate and the test project to Umbraco 7.3 and deployed to
> Nuget.
> It is working for me, let me know how you get on.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nicbell/ucreate/issues/5#issuecomment-154170163.

## 

---

Med vänlig hälsning
Daniel Nordenström

Tel: 073-642 29 37
Mail: Danor019@gmail.com

**Comment by nicbell** [comment]
Error caused by space in property `alias`
